apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsinstance-1-corefile
data:
  Corefile: |
    .:1053 {
      root /etc/coredns
      file db.example.org example.org {
        reload 2s
      }
      file db.0.0.10.in-addr.arpa 0.0.10.in-addr.arpa {
        reload 2s
      }
      auto db.example.org db.0.0.10.in-addr.arpa {
        reload 2s
      }
      errors
      health
      ready
      prometheus :9153
      reload 2s 1s
      log
    }
  db.example.org: |
    $ORIGIN example.org.
    @	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
            2017042761 ; serial
            7200       ; refresh (2 hours)
            3600       ; retry (1 hour)
            1209600    ; expire (2 weeks)
            3600       ; minimum (1 hour)
            )
        3600 IN NS a.iana-servers.net.
        3600 IN NS b.iana-servers.net.
    runner1 3 IN A 10.0.0.1
    runner2 3 IN A 10.0.0.2
    runner3 3 IN CNAME runner1
    runner4 3 IN A 10.0.0.4

  db.0.0.10.in-addr.arpa: |
    $ORIGIN 0.0.10.in-addr.arpa.
    @	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
            2017042761 ; serial
            7200       ; refresh (2 hours)
            3600       ; retry (1 hour)
            1209600    ; expire (2 weeks)
            3600       ; minimum (1 hour)
            )
        3600 IN NS a.iana-servers.net.
        3600 IN NS b.iana-servers.net.
    1   IN PTR runner1.example.org.
    2   IN PTR runner2.example.org.
