# Default values for dns-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  name: dns-operator
  namespace: dns-operator

  image:
  # You should provide your own as no public image is available
    repository: "davidp1404/dns-operator"
    pullPolicy: "IfNotPresent"
    tag: "latest"
    imagePullSecrets: []

  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
     cpu: 250m
     memory: 250Mi

  nodeSelector: {}

  tolerations: []

  affinity: 
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "dns-operator"
        topologyKey: kubernetes.io/hostname
