apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.operator.name }}-templates
  namespace: {{ .Values.operator.namespace }}
data:
{{ (.Files.Glob "src/templates/*.j2").AsConfig | indent 2 }}

