apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.operator.name }}-app
  namespace: {{ .Values.operator.namespace }}
data:
{{ (.Files.Glob "src/*.py").AsConfig | indent 2 }}
