apiVersion: v1
data:
  configmap.j2: "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: dns-operator-{{name}}\n
    \ namespace: {{namespace}}\n  labels:\n    app.kubernetes.io/managed-by: \"dns-operator\"\n
    \   app: dns-operator-{{name}}\ndata:\n  Corefile: |\n    .:1053 {\n      root
    /etc/coredns\n      errors\n      health\n      ready\n      loadbalance round_robin\n
    \     prometheus :9153\n      reload 2s 1s\n      log\n      {% for zone in zonelist
    -%}\n      file db.{{zone}} {{zone}}\n      {% endfor -%}\n    }\n  {% for zone
    in zonelist -%}\n  db.{{zone}}: |\n    $ORIGIN {{zone}}.\n    @   3600 IN SOA
    sns.dns.icann.org. noc.dns.icann.org. (\n            2017042761 ; serial\n            7200
    \      ; refresh (2 hours)\n            3600       ; retry (1 hour)\n            1209600
    \   ; expire (2 weeks)\n            3600       ; minimum (1 hour)\n            )\n
    \       {% for ns in nslist -%}\n        3600 IN NS {{ns}}\n        {% endfor
    %}  \n    $TTL 5\n  {% endfor %}"
  deployment.j2: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name:  dns-operator-{{name}}
      namespace: {{namespace}}
      labels:
        app: dns-operator-{{name}}
        app.kubernetes.io/managed-by: "dns-operator"
    spec:
      selector:
        matchLabels:
          app: dns-operator-{{name}}
      revisionHistoryLimit: 10
      replicas: {{replicas}}
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 50%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: dns-operator-{{name}}
            app.kubernetes.io/managed-by: "dns-operator"
        spec:
          containers:
          - name:  main
            image: k8s.gcr.io/coredns/coredns:v1.8.4
            args:
            - -dns.port
            - "1053"
            - -conf
            - /etc/coredns/Corefile
            resources:
              requests:
                cpu: 250m
                memory: 250Mi
              limits:
                cpu: 250m
                memory: 250Mi
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ready
                port: 8181
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            ports:
            - containerPort: 1053
              name: dns
              protocol: UDP
            - containerPort: 1053
              name: dns-tcp
              protocol: TCP
            - containerPort: 9153
              name: metrics
              protocol: TCP
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
              readOnly: true
          restartPolicy: Always
          volumes:
          - name: config-volume
            configMap:
              name: dns-operator-{{name}}
              items:
              - key: Corefile
                path: Corefile
              {% for zone in zonelist -%}
              - key: db.{{zone}}
                path: db.{{zone}}
              {% endfor %}
  service-tcp.j2: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: dns-operator-tcp-{{name}}
      namespace: {{namespace}}
      labels:
        app: dns-operator-{{name}}
        app.kubernetes.io/managed-by: "dns-operator"
      annotations:
        metallb.universe.tf/allow-shared-ip: dns-operator-{{name}}
    spec:
      selector:
        app: dns-operator-{{name}}
      type: {{lbtype}}
      sessionAffinity: None
      ports:
      - name: dnstcp
        protocol: TCP
        port: 53
        targetPort: 1053
  service-udp.j2: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: dns-operator-udp-{{name}}
      namespace: {{namespace}}
      labels:
        app: dns-operator-{{name}}
        app.kubernetes.io/managed-by: "dns-operator"
      annotations:
        metallb.universe.tf/allow-shared-ip: dns-operator-{{name}}
    spec:
      selector:
        app: dns-operator-{{name}}
      type: {{lbtype}}
      sessionAffinity: None
      ports:
      - name: dnstcp
        protocol: UDP
        port: 53
        targetPort: 1053
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dns-operator-templates
