apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns-operator
resources:
- namespace.yaml
- dns-operator-sa.yaml
- rbac.yaml
- dns-operator-templates.yaml
- dns-operator-app.yaml
- dns-operator-deployment.yaml