---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: foo.sample.org
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: A
  zone: sample.org
  recordKey: "foo"
  recordValue: ["10.0.0.2"]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: bar.sample.org
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: A
  zone: sample.org
  recordKey: "bar"
  recordValue: ["10.0.0.1","10.0.0.3"]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: foo-inv.sample.org
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "2"
  recordValue: ["foo.sample.org."]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: bar-inv1.sample.org
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "1"
  recordValue: ["bar.sample.org."]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: bar-inv3.sample.org
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "3"
  recordValue: ["bar.sample.org."]
---
