---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record1
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: A
  zone: sample.org
  recordKey: "record1"
  recordValue: ["10.0.0.1"]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record2
spec:
  dnsServerRef: sample.org
  recordType: A
  zone: sample.org
  recordKey: "record2"
  recordValue: ["10.0.0.1","10.0.0.3"]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record3
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "3"
  recordValue: ["record3.sample.org."]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record4
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "4"
  recordValue: ["record4.sample.org."]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record5
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "5"
  recordValue: ["record5.sample.org."]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record6
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: CNAME
  zone: sample.org
  recordKey: "record6"
  recordValue: ["record1.sample.org."]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record7
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: AAAA
  zone: sample.org
  recordKey: "record7"
  recordValue: ["2002:7f00:0:1::1"]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record8
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 1.0.0.0.0.0.0.0.0.0.f.7.2.0.0.2.ip6.arpa
  recordKey: "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0"
  recordValue: ["record8.sample.org."]
