---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record6
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: CNAME
  zone: sample.org
  recordKey: "record6"
  recordValue: ["record1.sample.org."]
