---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record5
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "5"
  recordValue: ["record5.sample.org."]
