---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record4
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: PTR
  zone: 0.0.10.in-addr.arpa
  recordKey: "4"
  recordValue: ["record4.sample.org."]
