---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record7
  namespace: default
spec:
  dnsServerRef: sample.org
  recordType: AAAA
  zone: sample.org
  recordKey: "record7"
  recordValue: ["2002:7f00:0:1::1"]
