apiVersion: davidp1404.github.com/v1
kind: dnsServer
metadata:
  name: sample.org
  namespace: default
spec:
#  provider: "corednsFiles"
  zones: 
  - sample.org
  - 0.0.10.in-addr.arpa
#  replicas: 2
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record1.sample.org
  namespace: default
spec:
  recordType: A
  zone: sample.org
  recordKey: "foo"
  recordValue: ["10.0.0.1"]
---
apiVersion: davidp1404.github.com/v1
kind: dnsRecord
metadata:
  name: record2.sample.org
  namespace: default
spec:
  recordType: A
  zone: sample.org
  recordKey: "bar"
  recordValue: ["10.0.0.2","10.0.0.3"]
