---
apiVersion: davidp1404.github.com/v1
kind: dnsServer
metadata:
  name: sample.org
  namespace: default
spec:
#  provider: "corednsFiles"
  zones: 
  - sample.org
  - 0.0.10.in-addr.arpa
#  replicas: 2

